# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  build:
    docker:
      - image: circleci/ruby:2.3

  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            echo "nuevo"

  deploy: &deploy
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "holaaa1133"

  deploy-staging:
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "otro coso"
          echo "otro coso"
          echo "otro coso"
          echo "$TT"

  deploy-prod:
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "holaaa3"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
            - deploy
          filters:
            branches:
              only: staging
          context: staging

      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
          context: prodution
