# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            echo "$TT"

  deploy: &deploy
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "$TT"

  deploy-staging:
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "$TT"

  deploy-prod:
    docker:
     - image: circleci/python:3.6.1
    steps:
     - run:
        name: install dependencies
        command: |
          echo "$TT"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
      - deploy-staging:
          requires:
            - - hold
          filters:
            branches:
              only: staging
          context: staging

      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
          context: production
